# -*- coding: utf-8 -*-
"""analisedadoslojadeeletronicos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zH5ccgOKdtWlgo46HPjzfTW8I1H-zkg1
"""

# 1 percorrer todos os arquivos da pasta vendas 
import os 
import pandas as pd

lista_arquivo = os.listdir('/content/drive/MyDrive/01-20 - Curso de Python - Aula 2/Vendas')
display(lista_arquivo)

# 2 importar a base de dados

tabela_total = pd.DataFrame()

for arquivo in lista_arquivo:
  if "Vendas" in arquivo: 
    # importar o arquivo 
    tabela = pd.read_csv(f"/content/drive/MyDrive/01-20 - Curso de Python - Aula 2/Vendas/{arquivo}")
    tabela_total = tabela_total.append(tabela)

# 3 tratar / compilar as bases de dados
display(tabela_total)

# 4 calcular o produto mais vendido (quantidade)
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[["Quantidade Vendida"]].sort_values(by="Quantidade Vendida", ascending=False)
display(tabela_produtos)
# tabela_produtos = tabela_total[["Produto","Quantidade Vendida"]].sort_values(by="Quantidade Vendida", ascending=True)

# 5 calcular o produto que mais faturou (faturamento)
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']

tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[["Faturamento"]].sort_values(by="Faturamento", ascending=False)
display(tabela_faturamento)

# 6 calcular loja/cidade que mais vendeu (em faturamento) - criar um gráfico/dashboard

tabela_lojas = tabela_total.groupby("Loja").sum()
tabela_lojas = tabela_lojas[['Quantidade Vendida']].sort_values(by="Quantidade Vendida", ascending=False)
display(tabela_lojas)

import plotly.express as px

grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Quantidade Vendida')
grafico.show()